/* app.js — renders flagged basins on a Google Hybrid basemap and shows each
 * model's forecast when a basin is clicked.
 *
 * Data comes from window.FLOOD_DATA (a GeoJSON FeatureCollection generated by
 * build_basins.py). Each feature.properties has: basin_id, severity (worst
 * across models), model_count, and forecasts (the full per-model list).
 */

(function () {
  "use strict";

  // Severity -> colour. Keep in sync with the CSS legend / palette.
  const SEVERITY = {
    none:     { rank: 0, color: "#7d8b99", label: "None" },
    minor:    { rank: 1, color: "#ffe08a", label: "Minor" },
    moderate: { rank: 2, color: "#ffc24d", label: "Moderate" },
    major:    { rank: 3, color: "#ff8a3d", label: "Major" },
    severe:   { rank: 4, color: "#ff4d4d", label: "Severe" },
    extreme:  { rank: 5, color: "#b026ff", label: "Extreme" },
  };
  const DEFAULT_COLOR = "#4da3ff";

  function sevColor(s) {
    const k = (s || "").toLowerCase();
    return SEVERITY[k] ? SEVERITY[k].color : DEFAULT_COLOR;
  }

  // Human labels for the forecast fields we know about (order matters).
  const FIELD_LABELS = [
    ["severity", "Severity"],
    ["riverId", "River ID"],
    ["returnPeriodYr", "Return period"],
    ["peakDischargeCms", "Peak discharge"],
    ["issuedTime", "Issued"],
    ["startTime", "Start"],
    ["peakTime", "Peak"],
    ["endTime", "End"],
    ["historicalComparison", "Historical"],
  ];

  function fmtValue(key, val) {
    if (val === undefined || val === null || val === "") return "—";
    if (key === "returnPeriodYr") return val + "-year";
    if (key === "peakDischargeCms") return val + " m³/s";
    if (key.endsWith("Time")) {
      const d = new Date(val);
      if (!isNaN(d)) {
        return d.toLocaleString(undefined, {
          month: "short", day: "numeric", hour: "2-digit", minute: "2-digit",
          hour12: false, timeZoneName: "short",
        });
      }
    }
    return String(val);
  }

  // ---- Map setup ------------------------------------------------------------
  const map = L.map("map", { zoomControl: true, minZoom: 2, maxZoom: 20 });

  const googleAttr = "Imagery &copy; Google · Basins: HydroBASINS (HydroSHEDS)";
  const googleSub = ["mt0", "mt1", "mt2", "mt3"];

  // Selectable basemaps. lyrs=y = hybrid (imagery + labels), lyrs=s = satellite.
  const baseLayers = {
    "Google Hybrid": L.tileLayer("https://{s}.google.com/vt/lyrs=y&x={x}&y={y}&z={z}", {
      subdomains: googleSub, maxZoom: 20, attribution: googleAttr,
    }),
    "Google Satellite": L.tileLayer("https://{s}.google.com/vt/lyrs=s&x={x}&y={y}&z={z}", {
      subdomains: googleSub, maxZoom: 20, attribution: googleAttr,
    }),
    "OpenStreetMap": L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", {
      maxZoom: 19,
      attribution: "&copy; OpenStreetMap contributors · Basins: HydroBASINS (HydroSHEDS)",
    }),
  };

  // Default basemap.
  baseLayers["Google Hybrid"].addTo(map);

  // Toggle control (top-right, expanded so all three options are visible).
  L.control.layers(baseLayers, null, { position: "topright", collapsed: false }).addTo(map);

  // ---- Legend ---------------------------------------------------------------
  const legendEl = document.getElementById("legend");
  legendEl.innerHTML = Object.keys(SEVERITY)
    .filter((k) => k !== "none")
    .map((k) => `<span class="item"><span class="swatch" style="background:${SEVERITY[k].color}"></span>${SEVERITY[k].label}</span>`)
    .join("");

  // ---- Panel ----------------------------------------------------------------
  const panelEmpty = document.getElementById("panel-empty");
  const panelContent = document.getElementById("panel-content");

  function showBasin(props) {
    panelEmpty.hidden = true;
    panelContent.hidden = false;

    const worst = (props.severity || "").toLowerCase();
    const worstColor = sevColor(worst);

    const cards = props.forecasts.map((fc) => {
      const rows = FIELD_LABELS
        .filter(([k]) => k !== "historicalComparison")
        .map(([k, label]) => {
          if (k === "severity") {
            const c = sevColor(fc.severity);
            return `<dt>${label}</dt><dd><span class="badge" style="background:${c}">${fc.severity || "—"}</span></dd>`;
          }
          return `<dt>${label}</dt><dd>${fmtValue(k, fc[k])}</dd>`;
        })
        .join("");
      const note = fc.historicalComparison
        ? `<div class="note">“${fc.historicalComparison}”</div>` : "";
      return `
        <div class="card" style="border-left-color:${sevColor(fc.severity)}">
          <div class="card-head">
            <span class="model">${(fc.model || "model").replace(/_/g, " ")}</span>
          </div>
          <dl class="kv">${rows}</dl>
          ${note}
        </div>`;
    }).join("");

    panelContent.innerHTML = `
      <h2>Basin ${props.basin_id}
        <span class="badge" style="background:${worstColor}">${worst || "—"}</span>
      </h2>
      <p class="subtitle">${props.model_count} model forecast${props.model_count === 1 ? "" : "s"} · worst-case shown above</p>
      ${cards}`;
  }

  // ---- Basin layer ----------------------------------------------------------
  const data = window.FLOOD_DATA;
  if (!data || !data.features || !data.features.length) {
    document.getElementById("panel-empty").innerHTML =
      "<h2>No basin data</h2><p>Run <code>python build_basins.py</code> to generate <code>data.js</code>.</p>";
    map.setView([46.7, -123.2], 9);
    return;
  }

  function baseStyle(feature) {
    const c = sevColor(feature.properties.severity);
    return { color: c, weight: 2, opacity: 1, fillColor: c, fillOpacity: 0.35 };
  }
  const HOVER_STYLE = { weight: 3, fillOpacity: 0.55 };

  let selected = null;

  function clearSelection() {
    if (selected) { layer.resetStyle(selected); selected = null; }
    panelContent.hidden = true;
    panelEmpty.hidden = false;
  }

  const layer = L.geoJSON(data, {
    style: baseStyle,
    onEachFeature: function (feature, lyr) {
      const p = feature.properties;
      lyr.bindTooltip(
        `Basin ${p.basin_id} · <b>${p.severity || "?"}</b> (${p.model_count} model${p.model_count === 1 ? "" : "s"})`,
        { sticky: true }
      );
      lyr.on({
        mouseover: () => { if (lyr !== selected) lyr.setStyle(HOVER_STYLE); },
        mouseout: () => { if (lyr !== selected) layer.resetStyle(lyr); },
        click: (e) => {
          L.DomEvent.stopPropagation(e);  // don't let it reach the map-click deselect
          if (selected) layer.resetStyle(selected);
          selected = lyr;
          lyr.setStyle({ weight: 4, fillOpacity: 0.55, color: "#ffffff" });
          showBasin(p);
          map.fitBounds(lyr.getBounds(), { maxZoom: 12, padding: [40, 40] });
        },
      });
    },
  }).addTo(map);

  // Click empty map (not a basin) to deselect.
  map.on("click", clearSelection);

  map.fitBounds(layer.getBounds(), { padding: [60, 60], maxZoom: 11 });
})();
