#!/usr/bin/env python3
"""
build_basins.py — join flood forecasts to basin geometry for the map UI.
Will be replaced by pulls from the bucket in future.

Reads:
  ../flood_state.json   the forecast list (one entry per model-per-basin)
  ../HUC12.parquet      HydroBASINS level-12 polygons (key column: HYBAS_ID)

Writes:
  data.js               window.FLOOD_DATA = <GeoJSON FeatureCollection>

Only the basins referenced in flood_state.json are pulled out of the (huge,
~1M row) parquet, so the browser loads a tiny file. Each output feature carries:
  - basin_id
  - forecasts: the list of every model's forecast for that basin
  - severity:  the highest severity across its models (used for colouring)

We emit a .js file (not .geojson) so index.html can be opened directly from
disk — a plain <script> tag loads it, no local web server required.

Re-run this whenever flood_state.json changes:
    python build_basins.py
"""

import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)                      # RFS-FEWS_Share/
FLOOD_JSON = os.path.join(ROOT, "flood_state.json")
PARQUET = os.path.join(ROOT, "HUC12.parquet")
OUTPUT = os.path.join(HERE, "data.js")

# Severity low -> high; the max across a basin's models drives its colour.
SEVERITY_RANK = {
    "none": 0, "minor": 1, "moderate": 2, "major": 3, "severe": 4, "extreme": 5,
}


def load_forecasts(path):
    """Return {basin_id(str): [forecast, ...]} grouped from the flat JSON list."""
    with open(path, encoding="utf-8") as f:
        entries = json.load(f)
    grouped = {}
    for e in entries:
        bid = str(e.get("basinId", "")).strip()
        if bid:
            grouped.setdefault(bid, []).append(e)
    return grouped


def worst_severity(forecasts):
    best = ""
    best_rank = -1
    for fc in forecasts:
        r = SEVERITY_RANK.get(str(fc.get("severity", "")).lower(), -1)
        if r > best_rank:
            best_rank, best = r, str(fc.get("severity", "")).lower()
    return best


def load_geometry(path, wanted_ids):
    """Stream the parquet, returning {hybas_id(int): geojson_geometry} for wanted ids."""
    try:
        import pyarrow.parquet as pq
        from shapely import wkb
        from shapely.geometry import mapping
    except ImportError as e:
        sys.exit(
            f"Missing dependency: {e.name}. Install with:\n"
            f"    pip install pyarrow shapely"
        )

    want = {int(x) for x in wanted_ids}
    out = {}
    pf = pq.ParquetFile(path)
    for batch in pf.iter_batches(batch_size=200_000, columns=["HYBAS_ID", "geometry"]):
        d = batch.to_pydict()
        for hid, geom in zip(d["HYBAS_ID"], d["geometry"]):
            if hid in want and hid not in out:
                out[hid] = mapping(wkb.loads(bytes(geom)))
        if len(out) == len(want):
            break
    return out


def main():
    if not os.path.exists(FLOOD_JSON):
        sys.exit(f"Not found: {FLOOD_JSON}")
    if not os.path.exists(PARQUET):
        sys.exit(f"Not found: {PARQUET}")

    forecasts = load_forecasts(FLOOD_JSON)
    print(f"Forecasts cover {len(forecasts)} basin(s): {', '.join(forecasts)}")

    geom = load_geometry(PARQUET, forecasts.keys())
    missing = [b for b in forecasts if int(b) not in geom]
    if missing:
        print(f"  warning: no geometry in parquet for: {', '.join(missing)}",
              file=sys.stderr)

    features = []
    for bid, fcs in forecasts.items():
        g = geom.get(int(bid))
        if g is None:
            continue
        features.append({
            "type": "Feature",
            "geometry": g,
            "properties": {
                "basin_id": bid,
                "severity": worst_severity(fcs),
                "model_count": len(fcs),
                "forecasts": fcs,
            },
        })

    fc = {"type": "FeatureCollection", "features": features}
    with open(OUTPUT, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by build_basins.py — do not edit by hand.\n")
        f.write("window.FLOOD_DATA = ")
        json.dump(fc, f, ensure_ascii=False)
        f.write(";\n")
    print(f"Wrote {len(features)} basin feature(s) -> {OUTPUT}")


if __name__ == "__main__":
    main()
